- name: PHP service playbook
  hosts: test
  become: yes
  become_user: root
  tasks:
    - name: delete old con and create new container test srv
      shell: docker rm -f my-php-app     
      shell: docker run -dt --name my-php-app -p 8081:8080 52.140.57.198:5000/my-php-app:"{{ tag }}"
